### PR TITLE
Googleapis module

### PR DESCRIPTION
**Pull request by btsimonh**
Happy to present a Berry module which offers auth to Google APIs, using Google Drive as an example.

### CODE REVIEW

**Comment by dkebler** [comment]
looks like you still have to move that you added to the root README to modules/README.md 

And sorry I just  I made some changes to the root readme (in main) so pull the latest commit before you do that.

**Comment by btsimonh** [comment]
yep, I think I mis-read the instructions again :).  Will sort out tonight.

**Comment by btsimonh** [comment]
ok, I've made the link from the modules readme go to the folder - since the readme is displayed below the folder list anyway.
This is my preferred way to see smallish folders within a repo - thoughts?

**Comment by dkebler** [comment]
great.  Thx.  our first merged contribution!  Now I have to work on my first.

**Pull request merged**
